config/routes.rb
Lifehacks::Application.routes.draw do
  
  root :to => 'home#index'
  resources :users
  resources :courses
  resources :ebooks
  resources :videos
  resources :categories
  resources :notes

  get '/logout' => 'sessions#destroy'
  post '/login' => 'sessions#create'
  
  get 'dashboard' => 'home#dashboard'

  match '/auth/:provider/callback' => 'sessions#twittercreate'
  match '/auth/failure' => redirect('/')
  get '/search' => 'search#index'
  get '/query' => 'search#query'
  post '/vote' => 'votes#vote'
  post '/save' => 'courses#save'
  post '/follow' => 'users#follow'
  post '/unfollow' => 'users#unfollow'
  get '/popular' => 'courses#popular'
  get '/usersearch' => 'users#search'
  get '/userquery' => 'users#userquery'
 
  mount Foundation::Icons::Rails::Engine => '/fi'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  first_name      :string(255)
#  last_name       :string(255)
#  zip             :integer
#  image           :string(255)
#  is_admin        :string(255)
#  is_teacher      :string(255)
#  is_pro          :string(255)
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  full_name       :string(255)
#  uid             :string(255)
#  provider        :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :full_name, :password, :password_confirmation, :is_admin, :is_teacher, :is_pro, :description, :uid, :provider, :remote_image_url

  has_secure_password
  # validates :email, :password_digest, :presence => true
  # validates :email, :uniqueness => true
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :courses
  has_many :taught_courses, :class_name => 'Course', :foreign_key => 'teacher_id'
  has_many :notes, :through => :courses
  has_many :events

  mount_uploader :image, ImageUploader

  def self.text_search(query)
    self.where("full_name @@ :q", :q => query)
  end

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    user = User.new
    user.full_name = auth[:info][:name]
    user.uid = auth[:uid]
    user.provider = auth[:provider]
    user.remote_image_url = "http://bossymoksie.files.wordpress.com/2012/06/blank_avatar_220.png"

    pass = (0...50).map{ ('a'..'z').to_a[rand(26)] }.join

    user.password = pass
    user.password_confirmation = pass
    user.save
    user
  end

  acts_as_voter

  acts_as_followable
  acts_as_follower
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    full_name = params[:full_name]
    email = params[:email]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    @user = User.create(:full_name => full_name, :email => email, :password => password, :password_confirmation => password_confirmation, :remote_image_url => "http://bossymoksie.files.wordpress.com/2012/06/blank_avatar_220.png")
    session[:user_id] = @user.id

    redirect_to dashboard_path
  end

  def edit
    if params[:id].to_i == @auth.id
      @user = User.find(params[:id])
    else
      redirect_to dashboard_path
    end
  end

  def show
    @user = User.find(params[:id])
    @courses_by = Course.where(:teacher_id => @user.id).page(params[:page])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end

  def follow
    @user = User.find(params[:user_id])
    follower = @auth
    follower.follow(@user)
  end

  def unfollow 
    @user = User.find(params[:user_id])
    @auth.stop_following(@user)
  end

  def search

  end

  def userquery
    query = params[:query]
      if query.present?
        @users = User.text_search(query).page(params[:page])
      else
        @users = User.page(params[:page])
      end
    end
end

app/views/users/_profile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/follow.js.erb
$('#follow-button').empty();

$('#follow-button').prepend('<%=j button_to('Unfollow', unfollow_path(:user_id => @user.id), :class => 'button', :method => :post, :remote => true) %>');

    

app/views/users/index.html.erb
<div class="twelve columns">
  <h2>Users</h2>
</div>

<div class="twelve columns">
<ul>
  <% @users.each do |user| %>
    <%= render :partial => 'shared/userdiv', :locals => { :user => user }  %>
  <% end %>
  <%= paginate @users %>
</ul>
</div>

app/views/users/search.html.erb
<div class="twelve columns">
  <h2>Search Users</h2>
</div>

<div class="twelve columns">
  <div id="search_form" class="six columns">
    <%= form_tag '/userquery', :method => :get, :remote => true do %>
      <%= text_field_tag 'query', nil, :placeholder => 'Search for users', :class => 'search-query' %>
      <%= submit_tag 'Submit', :class => 'button' %>
    <% end %>
  </div>
</div>

<div id="search_results" class="twelve columns">

</div>

app/views/users/show.html.erb
<div class="twelve columns">
  <h2><%= @user.full_name %></h2>
</div>

<div class="twelve columns">
  <div class="avatar two columns th">
    <%= image_tag @user.image.url %>
    <div id="follow-button">
      <% if @auth && @auth.following?(@user) %>
        <%= button_to('Unfollow', unfollow_path(:user_id => @user.id), :class => 'button', :method => :post, :remote => true) %>
      <% else %>
        <%= button_to('Follow', follow_path(:user_id => @user.id), :class => 'button', :method => :post, :remote => true) %>
      <% end %>
    </div>
    <%= render :partial => 'shared/followbox', :locals => { :user => @user }  %>
  </div>

  <% if @courses_by.any? %>
    <div id="courses_by" class="five columns">
      <h3>Courses By This User</h3>
      <ul class="unstyled">
        <% @courses_by.each do |course| %>
          <%= render :partial => 'shared/bigcoursediv', :locals => { :course => course }  %>
        <% end %>
      </ul>
      <%= paginate @courses_by %>
    </div>
  <% else %>
  <% end %>

  <div id="user_courses" class="five columns end">
    <h3><%= @user.full_name %>'s Saved Courses</h3>
      <% if @user.courses.any? %>
        <ul class="accordion">
          <% @user.courses.each do |course| %>
            <li>
              <div class="title">
                <%= link_to course.title, course %>
              </div>
              <div class="content">
                <h4>Notes</h4>
                <% notes_array = Note.where(:course_id => course.id).where(:user_id => @user.id) %> 
                <% notes_array.each do |note| %>
                  <%= render :partial => 'shared/yournote', :locals => { :note => note }  %>
                <% end %>
              </div>
            </li> 
          <% end %>
        </ul>
      <% else %>
        <p><%= @user.full_name %> hasn't saved any courses yet!</p>
      <% end %>
  </div>

</div>

app/views/users/unfollow.js.erb
$('#follow-button').empty();

$('#follow-button').prepend('<%= button_to('Follow', follow_path(:user_id => @user.id), :class => 'button', :method => :post, :remote => true) %>');

    

app/views/users/userquery.js.erb
$('#search_results').empty();

<% if @users.count > 0 %>
  <% @users.each do |user| %>
    var userdiv  = $('<div>');
    var userpill = $('<div>');
    userdiv.addClass('course_div three columns');
    userpill.addClass('course_pill panel');
    $(userpill).prepend('<span="followers">Followers <%= user.followers_count %></span>');
    $(userpill).prepend('<h4><%= link_to user.full_name, user %></h4>');
    $(userpill).prepend('<%= link_to image_tag(user.image.url), user %>');
    $(userdiv).prepend(userpill);
    $('#search_results').prepend(userdiv);
  <% end %>
    $('#search_results').append('<%=j paginate @users, :remote => true %>')
<% else %>
  $('#search_results').prepend('<h2>No Results Matched Your Query!</h2>');
<% end %>

$('#search_results').prepend('<h2>Search Results</h2>');