config/routes.rb
Lifehacks::Application.routes.draw do
  
  root :to => 'home#index'
  resources :users
  resources :courses
  resources :ebooks
  resources :videos
  resources :categories
  resources :notes

  get '/logout' => 'sessions#destroy'
  post '/login' => 'sessions#create'
  
  get 'dashboard' => 'home#dashboard'

  match '/auth/:provider/callback' => 'sessions#twittercreate'
  match '/auth/failure' => redirect('/')
  get '/search' => 'search#index'
  get '/query' => 'search#query'
  post '/vote' => 'votes#vote'
  post '/save' => 'courses#save'
  post '/follow' => 'users#follow'
  post '/unfollow' => 'users#unfollow'
  get '/popular' => 'courses#popular'
  get '/usersearch' => 'users#search'
  get '/userquery' => 'users#userquery'
 
  mount Foundation::Icons::Rails::Engine => '/fi'

end

app/views/shared/_addaudio.html.erb
<div id="audio_form_wrapper">

  <fieldset>

    <legend>Add Audio</legend>

    <div class="field">
      <%= label_tag 'audio_title' %><br/>
      <%= text_field_tag 'audio_title' %>
    </div>

    <div class="field">
      <%= label_tag 'audio_file' %><br/>
      <%= file_field_tag 'audio_file' %>
    </div>

  </fieldset>
  
</div>

app/views/shared/_addebook.html.erb
<div id="ebook_form_wrapper">

  <fieldset>

    <legend>Add Ebook</legend>

    <div class="field">
      <%= label_tag 'ebook_title' %><br/>
      <%= text_field_tag 'ebook_title' %>
    </div>
    <div class="field">
      <%= label_tag 'ebook_file' %><br/>
      <%= file_field_tag 'ebook_file' %>
    </div>

    <div class="field">
      <%= label_tag 'ebook_image' %><br/>
      <%= file_field_tag 'ebook_image' %>
    </div>
  </fieldset>
</div>

app/views/shared/_addvideo.html.erb
<div id="video_form_wrapper">

  <fieldset>

    <legend>Add Video</legend>

    <div class="field">
      <%= label_tag 'video_title' %><br/>
      <%= text_field_tag 'video_title' %>
    </div>
    <div class="field">
      <%= label_tag 'video_link' %><br/>
      <%= text_field_tag 'video_link' %>
    </div>

  </fieldset>
</div>

app/views/shared/_audio.html.erb
<%= audio_tag audio_file, :controls => true %>

app/views/shared/_authnav.html.erb
<li class="has-dropdown">
  <%= link_to @auth.full_name, dashboard_path %>

  <ul class="dropdown">
    <li><%= link_to 'Logout', logout_path %></li>
  </ul>

</li>

app/views/shared/_coursediv.html.erb
<div class="course_div three columns th">
  <div class="course_pill panel">
    <%= link_to image_tag(course.image.url), course %>
    <h4><%= link_to course.title, course%></h4>
    <% category = course.categories.first %>
    <span class="votes">
      <span class="glyph social">a</span> <%= course.votes_for %> <span class="glyph social">b</span> <%= course.votes_against %>
    </span>
    <div class="category"><%= link_to category.name, category  %></div>
  </div>
</div>

app/views/shared/_ebook.html.erb
<%= link_to image_tag(ebook_image), ebook_file %>

app/views/shared/_followbox.html.erb
<% if user.all_following.any? %>
  <div class="twelve columns">
    <h4>Following</h4>
    <h4>
      <% user.all_following.each do |follow| %>
        <%= link_to follow.full_name, follow %>&nbsp;
      <% end %>
    </h4>
  </div>
<% end %>
<% if user.followers.any? %>
  <div class="twelve columns">
    <h4>Followed By</h4>
    <h4>
      <% user.followers.each do |follow| %>
        <%= link_to follow.full_name, follow %>&nbsp;
      <% end %>
    </h4>
  </div>
<% end %>

app/views/shared/_note.html.erb
<div class="note twelve columns panel">
  <div class="avatar two columns">
    <%= link_to image_tag(note.user.image), note.user %>
  </div>
  <div class="ten columns">
    <div class="twelve columns">
      <%= link_to note.user.full_name, note.user %> wrote on 
      <%= note.created_at.strftime("%d %b %Y") %>
    </div>
    <div class="twelve columns">
      <h4><%= note.subject %></h4>
    </div>
    <div class="twelve columns">
      <%= note.content %>
    </div>
  </div>
</div>

app/views/shared/_register.html.erb
<%= form_tag users_path, :class => 'form-inline' do %>
  <%= text_field_tag 'full_name', nil, :placeholder => "Username", :class => 'input-medium' %>
  <%= text_field_tag 'email', nil, :placeholder => "Email", :class => 'input-medium' %>
  <%= password_field_tag 'password', nil, :placeholder => "Password", :class => 'input-medium' %>
  <%= password_field_tag 'password_confirmation', nil, :placeholder => "Confirm password", :class => 'input-medium' %>
  <%= submit_tag 'Register', :class => 'btn' %>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag '/search', :class => 'navbar-search',  :method => :get, :remote => true do %>
  <%= text_field_tag 'query', nil, :placeholder => 'Search for courses', :class => 'search-query' %>
  <i class="icon-search"></i>
<% end %>

app/views/shared/_userdiv.html.erb
<div class="course_div three columns th">
  <div class="course_pill panel">
    <%= link_to image_tag(user.image.url), user %>
    <h4><%= link_to user.full_name, user %></h4>
    <span="followers">Followers <%= user.followers_count %></span>
  </div>
</div>

app/views/shared/_video.html.erb
<div class="flex-video widescreen">
  <iframe src="<%= video %>" width="960" height="540" frameborder="0" allowfullscreen></iframe> 
</div>

app/views/shared/_yournote.html.erb
<div class="note twelve columns panel">
  <div class="two columns">
    <%= note.created_at.strftime("%d %b %Y") %>
  </div>
  <div class="ten columns">
    <div class="twelve columns">
      <h4><%= note.subject %></h4>
    </div>
    <div class="twelve columns">
      <%= note.content %>
    </div>
    <div class="admin_links twelve columns">
      <%= link_to 'Edit note', edit_note_path(note) %> | <%= link_to 'Delete note', note, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>