config/routes.rb
Lifehacks::Application.routes.draw do
  
  root :to => 'home#index'
  resources :users
  resources :courses
  resources :ebooks
  resources :videos
  resources :categories
  resources :notes

  get '/logout' => 'sessions#destroy'
  post '/login' => 'sessions#create'
  
  get 'dashboard' => 'home#dashboard'

  match '/auth/:provider/callback' => 'sessions#twittercreate'
  match '/auth/failure' => redirect('/')
  get '/search' => 'search#index'
  get '/query' => 'search#query'
  post '/vote' => 'votes#vote'
  post '/save' => 'courses#save'
  post '/follow' => 'users#follow'
  post '/unfollow' => 'users#unfollow'
  get '/popular' => 'courses#popular'
  get '/usersearch' => 'users#search'
  get '/userquery' => 'users#userquery'
 
  mount Foundation::Icons::Rails::Engine => '/fi'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.page(params[:page])
  end

  def show
    course_id = params[:id]
    @course = Course.find(course_id)
    @teacher = User.find(@course.teacher_id)

    if @auth != nil
     @notes_array = Note.where(:course_id => @course.id).where(:user_id => @auth.id)
    end

    @all_notes_array = Note.where(:course_id => @course.id)
  end

  def new
    @course = Course.new
    teacher_objects = User.where(:is_teacher => "on")
    @teachers = teacher_objects.map {|teacher| ["#{teacher.first_name} #{teacher.last_name}"]  }
  end

  def edit
    if @auth.is_admin == "on"
      @course = Course.find(params[:id])
      teacher_objects = User.where(:is_teacher => "on")
      @teachers = teacher_objects.map {|teacher| ["#{teacher.first_name} #{teacher.last_name}"]  }
    else
      redirect_to dashboard_path
    end
  end

  def create

    c = Course.new

    c.title = params[:title]
    c.description = params[:description]
    c.price = params[:price]
    c.image_cache = params[:image_cache]
    c.remote_image_url = params[:remote_image_url]
    c.teacher_id = @auth.id


    cat_name = params[:category]
    category = Category.where(:name => cat_name).first

    if category.nil?
      category = Category.create(:name => cat_name, :page => 1)   
    end

    if params[:video_link] != ""
      v = Video.create(:title => params[:video_title], :link => params[:video_link])
      c.videos << v
    end

    if params[:ebook_file] != ""
      params[:ebook_title] ||= "Untitled"
      ebook = Ebook.create(:title => params[:ebook_title], :ebook_file => params[:ebook_file], :image => params[:ebook_image])
      c.ebooks << ebook
    end

    if params[:audio_file] != ""
      params[:audio_title] ||= "Untitled"
      audio = Audio.create(:title => params[:audio_title], :audio_file => params[:audio_file])
      c.audios << audio
    end

    c.save

    category.courses << c

    e = Event.create(:event => "#created a course", :user_id => @auth.id, :course_id => c.id)
    redirect_to courses_path

  end

  def update
    @course = Course.find(params[:id])

    if @course.update_attributes(params[:course])
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
    course = Course.find(params[:id])
    course.delete
    redirect_to courses_path
  end

  def save
    course = Course.find(params[:course_id])

    if @auth.courses.include? course
    else  
      @auth.courses << course
    end

    e = Event.create(:event  => "saved a course", :user_id => @auth.id, :course_id => course.id)
  
  end

  def popular
    @courses = Course.plusminus_tally.page(params[:page])
  end

end

app/views/courses/_form.html.erb
<div class="twelve columns">

<%=  form_tag(courses_path, :multipart => true) do %>  

  <div class="six columns">

    <fieldset>

      <legend>Course Information</legend>
    
      <div class="field">
        <%= label_tag 'title' %>
        <%= text_field_tag 'title' %>
      </div>

      <div class="field">
        <%= label_tag 'category' %>
        <%= text_field_tag 'category' %>
      </div>

      <div class="field">
        <%= label_tag 'description' %>
        <%= text_area_tag 'description', nil, :rows => "5" %>
      </div>

      <div class="field">
        <%= label_tag 'course_image' %>
        <%= file_field_tag 'course_image' %>
        <%= hidden_field_tag 'image_cache' %> 
        <%= text_field_tag 'remote_image_url', nil, :placeholder => "Or enter a url" %>
      </div>

      <div class="field">
        <%= image_tag( @course.image.thumb.url, :class => "edit-image")  if  @course.image? %>
      </div>
    
    </fieldset><!-- course info fieldset -->

    <div class="submit"><%= submit_tag %></div>

  </div>

    <div class="six columns">
     
      <fieldset>
        <legend>Add Media</legend>

        <div class="field">
          <input type="button" id="add_video" value="Add Video">
          <input type="button" id="add_ebook" value="Add Ebook" >
          <input type="button" id="add_audio" value="Add Audio">
        </div>

      </fieldset>

      <%= render 'shared/addvideo' %>
      <%= render 'shared/addebook' %>
      <%= render 'shared/addaudio' %>

    </div><!--end right six columns -->

  </div><!--end 12 column row-->

<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<div class="twelve columns">
  <h2>Courses</h2>
</div>

<div id="courses_index" class="twelve columns">
  <% @courses.each do |course| %>
    <%= render :partial => 'shared/coursediv', :locals => { :course => course }  %>
  <% end %>
  <%= paginate @courses %>
</div>

app/views/courses/new.html.erb
<div class="twelve columns">
  <h1>New Course</h1>
</div>

<%= render 'form' %>

app/views/courses/popular.html.erb
<div class="twelve columns">
  <h2>Popular Courses</h2>
</div>

<div id="courses_index" class="twelve columns">
  <% @courses.each do |course| %>
    <%= render :partial => 'shared/coursediv', :locals => { :course => course }  %>
  <% end %>
  <%= paginate @courses %>
</div>

app/views/courses/save.js.erb
$('#bookmark').empty();

$('#bookmark').prepend('<a class="button disabled" href="#">Course saved!</a>');

alertify.success( 'Course saved!' ); 

app/views/courses/show.html.erb
<div class="twelve columns">
<h2><%= @course.title %></h2>
</div>

<div class="eight columns clearfix">

  <% if @course.videos.any? %>
    <%= render :partial => 'shared/video', :locals => {:video => @course.videos.first.link} %>
  <% end %>

  <% if @course.ebooks.any? %>
    <%= render :partial => 'shared/ebook', :locals => {:ebook_file => @course.ebooks.first.ebook_file.url, :ebook_title => @course.ebooks.first.title, :ebook_image => @course.ebooks.first.image.url }  %>
  <% end %>

  <% if @course.audios.any? %>
    <%= render :partial => 'shared/audio', :locals => { :audio_title => @course.audios.first.title, :audio_file => @course.audios.first.audio_file }  %>
  <% end %>
</div>

<div class="four columns clearfix" id="notes">
  <h3>Notes</h3>
  <%= form_tag('/notes', :remote => true) do %>
    <%= text_field_tag 'subject' %>
    <%= text_area_tag 'content', nil, :rows => 13 %>
    <%= hidden_field_tag 'course_id', @course.id %>
    <%= submit_tag 'Save Notes', :class => 'button' %>
    <div class="note-alerts"></div>
  <% end %>
</div>

<div class="row">
  <div class="twelve columns">
    <div id="course-image" class="four columns">
      <%= link_to image_tag(@course.image.url), @teacher, :class => "th" %>
      <h3><%= link_to @teacher.full_name, @teacher %></h3>
      <h3>In
        <% @course.categories.each do |category| %>
          <%= link_to category.name, category %>
        <% end %>
      </h3>
      <h3>Users Who Have Added This Course</h3>
      <h3>
        <% @course.users.each do |user| %>
          <%= link_to user.full_name, user %>&nbsp;
        <% end %>
      </h3>
    </div>
      <div id="course-description" class="eight columns">

        <div id="vote-wrapper" class="row">

          <div id="social-buttons" class="five columns">
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style ">
              <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
              <a class="addthis_button_tweet"></a>
            </div>
            <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f7910806d51cb95"></script>
            <!-- AddThis Button END -->
          </div>
          
          <div id="updown" class="three columns">
            <div class="six columns">
              <%= link_to vote_path(:course_id => @course.id, :vote => "up"), :method => :post, :remote => true do %>
                <span class="glyph social">a</span>
              <% end %><br>
              <%= @course.votes_for %>
            </div>
            <div class="six columns">
              <%= link_to vote_path(:course_id => @course.id, :vote => "down"), :method => :post, :remote => true do %>
                <span class="glyph social">b</span>
              <% end %>
              <%= @course.votes_against %>
            </div>  
          </div>
          
          <div id="bookmark" class="four columns">
            <%= button_to('Add to Your Courses', save_path(:course_id => @course.id), :class => 'button', :method => :post, :remote => true) %>
          </div>
        </div>

        <dl class="tabs">
          <dd class="active"><a href="#simple1">Description</a></dd>
          <dd id="my-notes-tab"><a href="#simple2">My Notes (<%= my_note_numbers %>)</a></dd>
          <dd id="all-notes-tab"><a href="#simple3">All Notes (<%= all_note_numbers %>)</a></dd>
        </dl>
        <ul class="tabs-content">
          <li class="active" id="simple1Tab">
            <h2>Description</h2>
            <p><%= @course.description %></p>
          </li>
          <li id="simple2Tab">
            <div class="twelve columns">   
              <h2>My Notes</h2>
            </div>
            <div id="my-notes" class="twelve columns">
              <% if @auth != nil %>
                <% @notes_array.each do |note| %>
                  <%= render :partial => 'shared/yournote', :locals => { :note => note }  %>
                <% end %>
              <% else %>
                <p>No notes saved yet, type some above!</p>
              <% end %>
            </div>
          </li>
          <li id="simple3Tab">
            <div class="twelve columns">   
              <h2>All Notes</h2>
            </div>
            <div id="all-notes" class="twelve columns">
              <% @all_notes_array.each do |note| %>
                <%= render :partial => 'shared/note', :locals => { :note => note }  %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>

    <% if @auth != nil && @course.teacher_id == @auth.id || @auth != nil && @auth.is_admin == "on" %>
      <%= link_to 'Edit', edit_course_path %> | 
      <%= link_to 'Delete', @course, data: { confirm: 'Are you sure?' }, :method => :delete %>
    <% end %>
    </div>
  </div>
</div>