config/routes.rb
Lifehacks::Application.routes.draw do
  
  root :to => 'home#index'
  resources :users
  resources :courses
  resources :ebooks
  resources :videos
  resources :categories
  resources :notes

  get '/logout' => 'sessions#destroy'
  post '/login' => 'sessions#create'
  
  get 'dashboard' => 'home#dashboard'

  match '/auth/:provider/callback' => 'sessions#twittercreate'
  match '/auth/failure' => redirect('/')
  get '/search' => 'search#index'
  get '/query' => 'search#query'
  post '/vote' => 'votes#vote'
  post '/save' => 'courses#save'
  post '/follow' => 'users#follow'
  post '/unfollow' => 'users#unfollow'
  get '/popular' => 'courses#popular'
  get '/usersearch' => 'users#search'
  get '/userquery' => 'users#userquery'
 
  mount Foundation::Icons::Rails::Engine => '/fi'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Learnwithme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="fixed contain-to-grid">
    <nav class="top-bar">
      <ul>
        <li class="name"><h1><%= link_to 'Learnwithme', root_path %></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>
      <section>
        <ul class="left">
          <li><%= link_to "Search", search_path %></li>
          <li><%= link_to "Browse Categories", categories_path %></li>
          <li><%= link_to "Popular", popular_path %></li>
          <li><%= link_to "Users", usersearch_path %></li>
          <li><%= dynamic_create_course_link %></li>
        </ul>

        <ul class="right">
          <li><%= dynamic_login_links %></li>
        </ul>
      </section>
    </nav>
  </div>

  <div class="row" id="container">
      <%= yield %>
  </div><!--container-->



</body>
</html>